#!/bin/sh
# ${scoop.ps1}
if command -v pwsh.exe > /dev/null 2>&1; then
    # pwsh.exe -noprofile -ex unrestricted -file "${scoop.ps1}"  "$@"
    pwsh.exe -noprofile -ex unrestricted -command "Import-Module scoop-accelerator; . '${scoop.ps1}'" "$@"
else
    # powershell.exe -noprofile -ex unrestricted -file "${scoop.ps1}"  "$@"
    powershell.exe -noprofile -ex unrestricted -command "Import-Module scoop-accelerator; . '${scoop.ps1}'"  "$@"
fi
