#!/bin/sh
if command -v pwsh.exe > /dev/null 2>&1; then
    pwsh.exe -noprofile -ex unrestricted -command "${scoop-accelerator.ps1}; ${scoop-i18n.ps1}; ${scoop.ps1}" "$@"
else
    powershell.exe -noprofile -ex unrestricted -command "${scoop-accelerator.ps1}; ${scoop-i18n.ps1}; ${scoop.ps1}"  "$@"
fi
