scoop config sa-rule-github '^https://github.com -> https://v4.gh-proxy.org/https://github.com'
scoop config sa-rule-github-raw '^https://raw.githubusercontent.com -> https://v4.gh-proxy.org/https://raw.githubusercontent.com'
scoop config sa-rule-github-gist '^https://gist.githubusercontent.com -> https://v4.gh-proxy.org/https://gist.githubusercontent.com'
scoop config sa-rule-sourceforge '^https://downloads.sourceforge.net -> https://v4.gh-proxy.org/sourceforge/https://downloads.sourceforge.net'
scoop config sa-rule-nodejs '^https://nodejs.org/dist/ -> https://registry.npmmirror.com/-/binary/node/'
