name: Excavator

on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: "20 */4 * * *"

jobs:
  excavate:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main

      - name: Sync script from extras bucket
        run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/ModifyPSProfile.psm1" -OutFile "scripts\ModifyPSProfile.psm1"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "chore(ModifyPSProfile): sync script from extras bucket"

      - name: Excavate
        uses: ScoopInstaller/GithubActions@5bceeda181721d9d10a18fdcc3ddca6f33467ae6 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
