name: Commented Pull Request Handler

on:
  issue_comment:
    types:
      - created

jobs:
  commented_pr_handler:
    name: Commented Pull Request Handler
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.actor != 'renovate[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Commented Pull Request Handler
        uses: ScoopInstaller/GithubActions@5bceeda181721d9d10a18fdcc3ddca6f33467ae6 # main
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
